<template><button v-bind="$attrs" :type="type" :disabled="disabled" class="app-button" :class="{ 'app-button--icon-only':icon&&!label,'app-button--outlined':outlined }"><i v-if="icon" :class="icon" aria-hidden="true"></i><span v-if="label" class="app-button__label">{{ label }}</span><slot /></button></template>
<script setup lang="ts">
defineOptions({ inheritAttrs:false });
withDefaults(defineProps<{label?:string;icon?:string;disabled?:boolean;type?:"button"|"submit"|"reset";outlined?:boolean}>(),{type:"button",disabled:false,outlined:false});
</script>
<style scoped>
.app-button{min-height:3rem;display:inline-flex;align-items:center;justify-content:center;gap:.5rem;padding:.72rem 1rem;border:1px solid var(--br-line-strong,#77736b);border-radius:0;background:var(--br-panel-2,#242321);color:var(--br-text,#eceae4);font:800 .78rem/1 "Courier New",monospace;letter-spacing:.045em;text-transform:uppercase;cursor:pointer;transition:transform .15s ease,background-color .15s ease,border-color .15s ease}.app-button:hover:not(:disabled){border-color:var(--br-accent,#e34b32);background:var(--br-accent,#e34b32);color:var(--br-accent-text,#fff)}.app-button:active:not(:disabled){transform:translateY(1px)}.app-button:disabled{cursor:not-allowed;opacity:.48}.app-button--icon-only{width:3rem;padding:0}.app-button__label{white-space:nowrap}.p-button-primary,.p-button-info{background:var(--br-accent,#e34b32);border-color:var(--br-accent,#e34b32);color:var(--br-accent-text,#fff)}.p-button-success{background:var(--br-success,#35624a);border-color:var(--br-success-line,#78a187);color:var(--br-success-text,#fff)}.p-button-danger{background:var(--br-danger,#96382e);border-color:var(--br-danger-line,#e06a5c);color:var(--br-danger-text,#fff)}.p-button-warning{background:var(--br-warning,#806527);border-color:var(--br-warning-line,#c5a44e);color:var(--br-warning-text,#fff)}.p-button-text,.p-button-outlined,.app-button--outlined{background:transparent;color:var(--br-text,#eceae4)}.p-button-rounded{border-radius:0}
</style>
<style>
.modal-content button.app-button.p-button-text,.modal-content button.app-button.app-button--outlined,.modal-shell button.app-button.p-button-text,.modal-shell button.app-button.app-button--outlined,.cut-modal button.app-button.p-button-text,.cut-modal button.app-button.app-button--outlined{background:transparent!important;color:#141413!important;border-color:#141413!important}.modal-content button.app-button.p-button-text:hover:not(:disabled),.modal-content button.app-button.app-button--outlined:hover:not(:disabled),.modal-shell button.app-button.p-button-text:hover:not(:disabled),.modal-shell button.app-button.app-button--outlined:hover:not(:disabled),.cut-modal button.app-button.p-button-text:hover:not(:disabled),.cut-modal button.app-button.app-button--outlined:hover:not(:disabled){background:#141413!important;color:#fff!important;border-color:#141413!important}
</style>
